const notesPositions = [
  { id: 0, name: "C1", value: 134 },
  { id: 1, name: "D1", value: 124 },
  { id: 2, name: "E1", value: 113 },
  { id: 3, name: "F1", value: 104 },
  { id: 4, name: "G1", value: 94 },
  { id: 5, name: "A1", value: 84 },
  { id: 6, name: "B1", value: 74 },
  { id: 7, name: "C2", value: 64 },
  { id: 8, name: "D2", value: 54 },
  { id: 9, name: "E2", value: 44 },
  { id: 10, name: "F2", value: 34 },
  { id: 11, name: "G2", value: 24 },
  { id: 12, name: "A2", value: 14 },
];

const majorScales = [
  {
    id: 1,
    scaleName: "CMajor",
    notes: "C - D - E - F - G - A - B",
    scaleNotes: [
      {
        id: 1,
        name: "C1",
        type: "full",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 4,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
    ],
  },
  {
    id: 2,
    scaleName: "C#Major",
    notes: "C# - D# - F - F# - G# - A# - C",
    scaleNotes: [
      {
        id: 1,
        name: "C#1",
        type: "sharp",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 3,
    scaleName: "DbMajor",
    notes: "Db - Eb - F - Gb - Ab - Bb - C",
    scaleNotes: [
      {
        id: 1,
        name: "Db1",
        type: "flat",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 4,
    scaleName: "DMajor",
    notes: "D - E - F# - G - A - B - C#",
    scaleNotes: [
      {
        id: 1,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 5,
    scaleName: "D#Major",
    notes: "D# - F - G - G# - A# - C - D",
    scaleNotes: [
      {
        id: 1,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 6,
    scaleName: "EbMajor",
    notes: "Eb - F - G - Ab - Bb - C - D",
    scaleNotes: [
      {
        id: 1,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 7,
    scaleName: "EMajor",
    notes: "E - F# - G# - A - B - C# - D#",
    scaleNotes: [
      {
        id: 1,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 8,
    scaleName: "FMajor",
    notes: "F - G - A - A# - C - D - E",
    scaleNotes: [
      {
        id: 1,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "A#",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
    ],
  },
  {
    id: 9,
    scaleName: "F#Major",
    notes: "F# - G# - A# - B - C# - D# - F",
    scaleNotes: [
      {
        id: 1,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "A#",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "B",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 10,
    scaleName: "GbMajor",
    notes: "Gb - Ab - Bb - B - Db - Eb - F",
    scaleNotes: [
      {
        id: 1,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 11,
    scaleName: "GMajor",
    notes: "G - A - B - C - D - E - F#",
    scaleNotes: [
      {
        id: 1,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 12,
    scaleName: "G#Major",
    notes: "G# - A# - C - C# - D# - F - G",
    scaleNotes: [
      {
        id: 1,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 13,
    scaleName: "AbMajor",
    notes: "Ab - Bb - C - Db - Eb - F - G",
    scaleNotes: [
      {
        id: 1,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 14,
    scaleName: "AMajor",
    notes: "A - B - C# - D - E - F# - G#",
    scaleNotes: [
      {
        id: 1,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G#2",
        type: "sharp",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 15,
    scaleName: "A#Major",
    notes: "A# - C - D - D# - F - G - A",
    scaleNotes: [
      {
        id: 1,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 16,
    scaleName: "BbMajor",
    notes: "Bb - C - D - Eb - F - G - A",
    scaleNotes: [
      {
        id: 1,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 17,
    scaleName: "BMajor",
    notes: "B - C# - D# - E - F# - G# - A#",
    scaleNotes: [
      {
        id: 1,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G#2",
        type: "sharp",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A#2",
        type: "sharp",
        position: notesPositions[12].value,
      },
    ],
  },
];

const harmonicMinorScales = [
  {
    id: 1,
    scaleName: "CHarmonic Minor",
    notes: "C - D - D# - F - G - G# - B",
    scaleNotes: [
      {
        id: 1,
        name: "C1",
        type: "full",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 4,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 7,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
    ],
  },
  {
    id: 2,
    scaleName: "C#Harmonic Minor",
    notes: "C# - D# - E - F# - G# - A - C",
    scaleNotes: [
      {
        id: 1,
        name: "C#1",
        type: "sharp",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "E",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 4,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 3,
    scaleName: "DbHarmonic Minor",
    notes: "Db - Eb - E - Gb - Ab - A - C",
    scaleNotes: [
      {
        id: 1,
        name: "Db1",
        type: "flat",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 4,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 4,
    scaleName: "DHarmonic Minor",
    notes: "D - E - F - G - A - A# - C#",
    scaleNotes: [
      {
        id: 1,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 5,
    scaleName: "D#Harmonic Minor",
    notes: "D# - F - F# - G# - A# - B - D",
    scaleNotes: [
      {
        id: 1,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "B2",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 6,
    scaleName: "EbHarmonic Minor",
    notes: "Eb - F - Gb - Ab - Bb - B - D",
    scaleNotes: [
      {
        id: 1,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "B2",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 7,
    scaleName: "EHarmonic Minor",
    notes: "E - F# - G - A - B - C - D#",
    scaleNotes: [
      {
        id: 1,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 8,
    scaleName: "FHarmonic Minor",
    notes: "F - G - G# - A# - C - C# - E",
    scaleNotes: [
      {
        id: 1,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "A#",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
    ],
  },
  {
    id: 9,
    scaleName: "F#Harmonic Minor",
    notes: "F# - G# - A - B - C# - D - F",
    scaleNotes: [
      {
        id: 1,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "A",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "B",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 10,
    scaleName: "GbHarmonic Minor",
    notes: "Gb - Ab - A - B - Db - D - F",
    scaleNotes: [
      {
        id: 1,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 11,
    scaleName: "GHarmonic Minor",
    notes: "G - A - A# - C - D - D# - F#",
    scaleNotes: [
      {
        id: 1,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 12,
    scaleName: "G#Harmonic Minor",
    notes: "G# - A# - B - C# - D# - E - G",
    scaleNotes: [
      {
        id: 1,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 13,
    scaleName: "AbHarmonic Minor",
    notes: "Ab - Bb - B - Db - Eb - E - G",
    scaleNotes: [
      {
        id: 1,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 14,
    scaleName: "AHarmonic Minor",
    notes: "A - B - C - D - E - F - G#",
    scaleNotes: [
      {
        id: 1,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G#2",
        type: "sharp",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 15,
    scaleName: "A#Harmonic Minor",
    notes: "A# - C - C# - D# - F - F# - A",
    scaleNotes: [
      {
        id: 1,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 16,
    scaleName: "BbHarmonic Minor",
    notes: "Bb - C - Db - Eb - F - Gb - A",
    scaleNotes: [
      {
        id: 1,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "Gb2",
        type: "flat",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 17,
    scaleName: "BHarmonic Minor",
    notes: "B - C# - D - E - F# - G - A#",
    scaleNotes: [
      {
        id: 1,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A#2",
        type: "sharp",
        position: notesPositions[12].value,
      },
    ],
  },
];

const melodicMinorScales = [
  {
    id: 1,
    scaleName: "CMelodic Minor",
    notes: "C - D - D# - F - G - A - B",
    scaleNotes: [
      {
        id: 1,
        name: "C1",
        type: "full",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "D#1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 4,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
    ],
  },
  {
    id: 2,
    scaleName: "C#Melodic Minor",
    notes: "C# - D# - E - F# - G# - A# - C",
    scaleNotes: [
      {
        id: 1,
        name: "C#1",
        type: "sharp",
        position: notesPositions[0].value,
      },
      {
        id: 2,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 3,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 4,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 5,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 6,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 3,
    scaleName: "DbMelodic Minor",
    notes: "Db - Eb - E - Gb - Ab - Bb - C",
    scaleNotes: [
      {
        id: 1,
        name: "Db1",
        type: "flat",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 4,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 4,
    scaleName: "DMelodic Minor",
    notes: "D - E - F - G - A - B - C#",
    scaleNotes: [
      {
        id: 1,
        name: "D1",
        type: "full",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 3,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 7,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
    ],
  },
  {
    id: 5,
    scaleName: "D#Melodic Minor",
    notes: "D# - F - F# - G# - A# - C - D",
    scaleNotes: [
      {
        id: 1,
        name: "D#1",
        type: "sharp",
        position: notesPositions[1].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 4,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 5,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 6,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 6,
    scaleName: "EbMelodic Minor",
    notes: "Eb - F - Gb - Ab - Bb - C - D",
    scaleNotes: [
      {
        id: 1,
        name: "Eb1",
        type: "flat",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 7,
    scaleName: "EMelodic Minor",
    notes: "E - F# - G - A - B - C# - D#",
    scaleNotes: [
      {
        id: 1,
        name: "E1",
        type: "full",
        position: notesPositions[2].value,
      },
      {
        id: 2,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 3,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 6,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 7,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
    ],
  },
  {
    id: 8,
    scaleName: "FMelodic Minor",
    notes: "F - G - G# - A# - C - D - E",
    scaleNotes: [
      {
        id: 1,
        name: "F1",
        type: "full",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 4,
        name: "A#",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 5,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
    ],
  },
  {
    id: 9,
    scaleName: "F#Melodic Minor",
    notes: "F# - G# - A - B - C# - D# - F",
    scaleNotes: [
      {
        id: 1,
        name: "F#1",
        type: "sharp",
        position: notesPositions[3].value,
      },
      {
        id: 2,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 3,
        name: "A",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "B",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 6,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 10,
    scaleName: "GbMelodic Minor",
    notes: "Gb - Ab - A - B - Db - Eb - F",
    scaleNotes: [
      {
        id: 1,
        name: "Gb1",
        type: "flat",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 5,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 11,
    scaleName: "GMelodic Minor",
    notes: "G - A - A# - C - D - E - F#",
    scaleNotes: [
      {
        id: 1,
        name: "G1",
        type: "full",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 4,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 7,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
    ],
  },
  {
    id: 12,
    scaleName: "G#Melodic Minor",
    notes: "G# - A# - B - C# - D# - F - G",
    scaleNotes: [
      {
        id: 1,
        name: "G#1",
        type: "sharp",
        position: notesPositions[4].value,
      },
      {
        id: 2,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 3,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 5,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 6,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 13,
    scaleName: "AbMelodic Minor",
    notes: "Ab - Bb - B - Db - Eb - F - G",
    scaleNotes: [
      {
        id: 1,
        name: "Ab1",
        type: "flat",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 4,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 14,
    scaleName: "AMelodic Minor",
    notes: "A - B - C - D - E - F# - G#",
    scaleNotes: [
      {
        id: 1,
        name: "A1",
        type: "full",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 3,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 6,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 7,
        name: "G#2",
        type: "sharp",
        position: notesPositions[11].value,
      },
    ],
  },
  {
    id: 15,
    scaleName: "A#Melodic Minor",
    notes: "A# - C - C# - D# - F - G - A",
    scaleNotes: [
      {
        id: 1,
        name: "A#1",
        type: "sharp",
        position: notesPositions[5].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 4,
        name: "D#2",
        type: "sharp",
        position: notesPositions[8].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 16,
    scaleName: "BbMelodic Minor",
    notes: "Bb - C - Db - Eb - F - G - A",
    scaleNotes: [
      {
        id: 1,
        name: "Bb1",
        type: "flat",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C2",
        type: "full",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "Db2",
        type: "flat",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "Eb2",
        type: "flat",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F2",
        type: "full",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G2",
        type: "full",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A2",
        type: "full",
        position: notesPositions[12].value,
      },
    ],
  },
  {
    id: 17,
    scaleName: "BMelodic Minor",
    notes: "B - C# - D - E - F# - G# - A#",
    scaleNotes: [
      {
        id: 1,
        name: "B1",
        type: "full",
        position: notesPositions[6].value,
      },
      {
        id: 2,
        name: "C#2",
        type: "sharp",
        position: notesPositions[7].value,
      },
      {
        id: 3,
        name: "D2",
        type: "full",
        position: notesPositions[8].value,
      },
      {
        id: 4,
        name: "E2",
        type: "full",
        position: notesPositions[9].value,
      },
      {
        id: 5,
        name: "F#2",
        type: "sharp",
        position: notesPositions[10].value,
      },
      {
        id: 6,
        name: "G#2",
        type: "sharp",
        position: notesPositions[11].value,
      },
      {
        id: 7,
        name: "A#2",
        type: "sharp",
        position: notesPositions[12].value,
      },
    ],
  },
];

export { majorScales, harmonicMinorScales, melodicMinorScales };
